[package]
name = "BubbleOS"
version = "0.1.0"
authors = ["babblet <frk.haha@hotmail.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
